version: '3.8'

services:
  api_mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastmcp_api_demo:latest
    container_name: fastmcp_api_demo
    ports:
      - "18000:8000"
    restart: unless-stopped