[project]
name = "fastmcp-api-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standarad,standard]>=0.124.4",
    "fastmcp>=2.14.1",
    "httpx>=0.28.1",
]
